### ISSUE TITLE
(v3.0 + Swift3.0)LineChart crash when dataSets is a empty array

### ISSUE THREAD

**Issue by Huang-Libo** [danielgindi/Charts#1491]
in v2.x,  when LineChart's dataSets  is a empty array it will show a charts with no line, but v3.0 will crash.

 error info：
fatal error: Double value cannot be converted to Int because it is either infinite or NaN

**Comment by danielgindi** [comment]
Try with latest master, there's a commit from a few hours ago that is supposed to fix that

**Comment by Huang-Libo** [comment]
@danielgindi 
I noticed the commit that you mentioned, and my version is just updated, but still crash.

**Comment by MonkeyRing** [comment]
<img width="668" alt="2016-09-21 5 30 56" src="https://cloud.githubusercontent.com/assets/8415820/18705646/9753dccc-8021-11e6-931b-bf938c1b0650.png">
master  -> Charts 3.0

**Comment by danielgindi** [comment]
This is fixed now due to another issue that has pointed out the source of the issue (#1511)

**Comment by apurva** [comment]
I can confirm that the fix does NOT work. Stepping through the code, I can see that the Number value 
starts at 1.7976931348623157E+308 and goes over the protection.  However, in this case,

`let i = roundToNextSignificant(number: Double(number))`

results in making i = infinity and then 

`Int(ceil(-log10(i))) + 2`

goes on to crash the app.

Why the initial number value is the max double value is beyond me though.

**Comment by liuxuan30** [comment]
@danielgindi reopened

**Comment by petester42** [comment]
Same issue as #1550. Should be fixed by #1558.

**Comment by quicklywilliam** [comment]
This issue is still at large. You can see the illegal conversion on this line (it tries to convert it to an Int inside the call to roundToNextSignificant):

https://github.com/danielgindi/Charts/blob/master/Source/Charts/Renderers/AxisRendererBase.swift#L125

**Comment by quicklywilliam** [comment]
If anyone is looking for a workaround for this without patching, just set custom axis min and max before setting the data on the chart, i.e.:

```
if (dataArray.count == 0) {
                chartView.xAxis.axisMinimum = 0
               chartView.xAxis.axisMaximum = 10
                
                chartView.leftAxis.axisMinimum = 0
                chartView.leftAxis.axisMaximum = 10
                chartView.rightAxis.axisMinimum = 0
                chartView.rightAxis.axisMaximum = 10
}
```

**Comment by semireg** [comment]
We're seeing this only when the chart is zoomed and we empty the data.
