### ISSUE TITLE
Selection in a bar chart

### ISSUE THREAD

**Issue by mattgallivan** [danielgindi/Charts#1530]
![screen shot 2016-09-22 at 9 31 52 am](https://cloud.githubusercontent.com/assets/20191266/18741495/747f4142-80a7-11e6-91b5-7f2dbd779c9e.png)

**Usage:** I am using a stacked bar chart with popovers. Everything is working and displaying correctly. The issue occurs during selection and deselection.

**Problem:** In the image above, the left bar is selected even when I click in the white space above it. That is to say, a bar is selected as long as I click anywhere in its column.

**Desired:** The desired effect would be to have a bar selected only when I click inside the bar (the green portion). The bar would be deselected when clicking anywhere else (the white portion).

Is this intended or am I missing a setting?

**Comment by rs10693** [comment]
Use **chartValueSelected** delegate. @mattgallivan

**Comment by Huang-Libo** [comment]
@mattgallivan 
This issue seems fixed now, pull new commits from master branch to check it.

**Comment by mattgallivan** [comment]
@Huang-Libo I have updated to the latest master branch and the issue still exists for me.

**Comment by KumaresanSubramaniam** [comment]
Bar chart plays too sensitive clicking event
