### ISSUE TITLE
Index out of bounds exception in v3.2 in createAccessibleElement

### ISSUE THREAD

**Issue by simonbengtsson** [danielgindi/Charts#3659]
After updating to charts 3.2 I started getting `Fatal error: Index out of range` in the new `BarChartRenderer#createAccessibleElement():809`. It seems this code `dataSet.stackLabels[idx % stackSize]` makes stackLabels required?

My workaround for now is to always specify `stackLabels`. Can be done with something like this:

```swift
let dataSet = BarChartDataSet(values: entries, label: nil)
dataSet.stackLabels = [String](repeating: "", count: dataSet.stackSize)
```

## Charts Environment

**Charts version:** 3.2
**Xcode version:** 10
**Swift version:** 4.2
**Platform:** iOS
**macOS:** 10.13.6

**Comment by liuxuan30** [comment]
@petester42 may have answer who's responsible for checking the bound for accessibility

**Comment by Talgat777** [comment]
+1 


1 | Charts | createAccessibleElement (ChartViewBase.swift:47)
2 | Charts | createAccessibleElement (<compiler-generated>:809)
3 | Charts | drawDataSet (HorizontalBarChartRenderer.swift:280)
4 | Charts | drawData (BarChartRenderer.swift:253)
5 | Charts | draw (BarLineChartViewBase.swift:231)

**Comment by AflyingApple** [comment]
I also encountered the same problem.

**Comment by nathantannar4** [comment]
+1

**Comment by nathantannar4** [comment]
@simonbengtsson's workaround still fails fit me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by petester42** [comment]
I believe I've fixed the issue but we should not allow setting colours/stackLabels individually. There are too many cases where they won't be of the some size but they should be. @liuxuan30, @danielgindi what do you guys think?

**Comment by petester42** [comment]
I've fixed the crashes but I found some accessibility issue with our current implementation. The fix will take a little longer

**Comment by petester42** [comment]
Problably the end of the week. I’ll see if I have time tomorrow. Please keep in mind that we are all just volunteering our time here.

**Comment by Scalman** [comment]
Hi, im still getting this error when using stacked bar chart. I can provide you with code if it is necessary!

**Error:**
Thread 1: Fatal error: Index out of range

**Where**
            elementValueText = dataSet.valueFormatter?.stringForValue(
                vals[idx % stackSize],                <-- HERE
                entry: e,
                dataSetIndex: dataSetIndex,
                viewPortHandler: viewPortHandler) ?? "\(e.y)"

**Charts Environment**
Charts version: 3.2.1
Xcode version: 10
Swift version: 4.2
Platform: iOS
macOS: 10.14

**Comment by Scalman** [comment]
Hi, here you go :).

Thanks in advance

```
import UIKit
import Charts

private class BarChartFormatter: NSObject, IAxisValueFormatter {
    
    var labels: [String] = []
    
    func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        return labels[Int(value)]
    }
    
    init(labels: [String]) {
        super.init()
        self.labels = labels
    }
}

class StackedChartView: BarChartView {
    
    lazy var formatter: NumberFormatter = {
        let formatter = NumberFormatter()
        formatter.maximumFractionDigits = 1
        formatter.negativeSuffix = " h"
        formatter.positiveSuffix = " h"
        return formatter
    }()
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        defaultSetup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        defaultSetup()
    }
    
    public func defaultSetup(){
        isUserInteractionEnabled = true
        self.pinchZoomEnabled = false
        scaleXEnabled = false
        scaleYEnabled = false
        drawGridBackgroundEnabled = false
        drawBarShadowEnabled = false
        drawValueAboveBarEnabled = false
        drawBordersEnabled = false
        drawMarkers = false
        legend.enabled = true
        drawBordersEnabled = false
        leftAxis.drawTopYLabelEntryEnabled = true
        leftAxis.drawAxisLineEnabled = false
        rightAxis.drawLabelsEnabled = false
        rightAxis.enabled = false
        leftAxis.drawLabelsEnabled = false
        leftAxis.enabled = false
        xAxis.drawAxisLineEnabled = true
        xAxis.drawGridLinesEnabled = false
        xAxis.drawLabelsEnabled = true
        chartDescription?.text = "DIS IS CHART DESCRIPTION. IT IS VERY BEAUTIFUL!"
        highlightFullBarEnabled = false
    }
    
    public func emptyChart(text:String){
        self.noDataText = text
    }

    public func drawChart(values:[WorkDay],titles:[String]){
        self.noDataText = "No data available"
        
        let count:Int = values.count
        
        let yVals = (0..<count).map { (i) -> BarChartDataEntry in
            
            let data = values[i].shifts!
            
            var shiftHours = [Double]()
            
            for shift in data{
                shiftHours.append(shift.hours!)
            }
            return BarChartDataEntry(x: Double(i), yValues: shiftHours, data: data as AnyObject)
        }
        
        let set = BarChartDataSet(values: yVals, label: "Stapeldiagram för dina pass denna vecka.")
        set.drawIconsEnabled = false
        set.colors = [ChartColorTemplates.material()[0], ChartColorTemplates.material()[1], ChartColorTemplates.material()[2]]
        set.stackLabels = ["Arbetade", "Lunch", "Missade"]
        
        
        let data = BarChartData(dataSet: set)
        data.setValueFont(.systemFont(ofSize: 7, weight: .light))
        data.setValueFormatter(DefaultValueFormatter(formatter: formatter))
        data.setValueTextColor(.white)
        
        
        self.fitBars = true
        self.data = data
        
        
        let labels = ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"]
        self.xAxis.valueFormatter = IndexAxisValueFormatter(values: labels)
        
        self.animate(xAxisDuration: 0, yAxisDuration: 1)
    }
}
```

**Comment by IGZJulianAlonso** [comment]
Also 4 me 😞

**Comment by jboulter11** [comment]
This is still not fixed by the above commit, using 3.2.1 and latest master both give me the same crash, even if I set the stack labels like suggested in the workaround.

The line crashing is:
```
elementValueText = dataSet.valueFormatter?.stringForValue(
                vals[idx % stackSize],
                entry: e,
                dataSetIndex: dataSetIndex,
                viewPortHandler: viewPortHandler) ?? "\(e.y)"
```

Specifically, `vals[idx % stackSize] is still being called when vals is empty.  The other references in this function were fixed, but not this one.

**Comment by Scalman** [comment]
Hi again,

I have read the comment above from @jboulter11 but what if you want one column with two segments and the other with four? The version 3.1.1 supported this feature. This works fine as long as you have fixed size segments in each column.

@petester42 what is the status on this issue

Many thanks again

**Comment by petester42** [comment]
The status is that I’ve not had the chance to work on it. Been busy. I don’t see myself being free until after Christmas. If you send a pull request fixing this I’ll review it and release a new version.

**Comment by liuxuan30** [comment]
Is it easy to fix guys? If so, please create a PR, I can review it soon and add it before next release coming soon.

**Comment by Scalman** [comment]
It was a while ago but i did found some time to fix the issue. @liuxuan30 @petester42 could one of review the small change i did. plz
