### ISSUE TITLE
Cannot install package v4.1.0 using SPM 

### ISSUE THREAD

**Issue by theedov** [danielgindi/Charts#4937]
I'm having a lot of compiling issues in Xcode14

https://github.com/danielgindi/Charts/issues/4873
https://github.com/danielgindi/Charts/issues/4646

When I try to install Charts using SPM the lates version I'm getting is v4.0.6.
Trying to manually set to v4.1.0 fails with error that it doesn't exist.

Does anyone know what can be wrong?

**Comment by theedov** [comment]
5 days letter and still have the same issue.
Weird....

**Comment by JosephCalla** [comment]
Same issue here

**Comment by JosephCalla** [comment]
I fixed it, but I don't remember

**Comment by JanC** [comment]
well, as I wrote above, using the exact version 4.1.0 fixes it

**Comment by theedov** [comment]
Still getting the same issue lol.
Setting the exact version seems to work.
